# This file is part of the BenGorUserBundle bundle.
#
# (c) Beñat Espiña <benatespina@gmail.com>
# (c) Gorka Laucirica <gorka.lauzirika@gmail.com>
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.

BenGor\User\Domain\Model\UserGuest:
    type: mappedSuperclass
    repositoryClass: BenGor\User\Infrastructure\Persistence\Doctrine\ODM\MongoDB\DoctrineODMMongoDBUserGuestRepository
    collection: user_guest
    fields:
        id:
            id: true
            type: user_guest_id
        email:
            type: user_email
        invitationToken:
            name: invitation_token
            type: user_token
        createdOn:
            name: created_on
            type: date
