# This file is part of the BenGorUser package.
#
# (c) Beñat Espiña <benatespina@gmail.com>
# (c) Gorka Laucirica <gorka.lauzirika@gmail.com>
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.

BenGorUser\User\Domain\Model\UserEmail:
    type: embeddable
    fields:
        email:
            column: email
            type: string
            length: 60
