# This file is part of the BenGorUserBundle bundle.
#
# (c) Beñat Espiña <benatespina@gmail.com>
# (c) Gorka Laucirica <gorka.lauzirika@gmail.com>
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.

BenGor\User\Domain\Model\UserPassword:
    type: embeddable
    fields:
        encodedPassword:
            column: password
            type: string
            length: 60
        salt:
            type: string
            length: 60
